/*
 * This file is distributed under the MIT License. See LICENSE.md for details.
 */

import { ComponentChild } from "preact";

// Interface describing the contents of `meta.yml`
export interface Metadata {
    extra_columns?: {
        name: string;
        label: string;
        renderer?: string;
        align?: "left" | "right";
    }[];

    downloads?: {
        name: string;
        label: string;
    }[];

    ordering?: {
        name: string;
        dir: "asc" | "desc";
    }[];

    notes?: string;
    reproducer_prelude?: string;
    highlights?: {
        query: string;
        description: string;
    }[];

    configurations?: {
        name?: string;
        timeout?: number;
        memory_limit?: number;
    }[];

    crash_components_filters?: {
        category: string;
        suffix: string;
        label: string;
    }[];

    // Autogenerated by `revng mass-testing run`
    cpu_count: number;
    start_time: number;
}

export interface StatusStats {
    total: number;
    totalTime: number;
    counts: Record<string, number>;
}

export interface StageEntry {
    name: string;
    count: number;
}

export interface ColumnDef {
    name: string;
    data?: string;
    title: string;
    className?: string;
    orderable?: boolean;
    searchable?: boolean;
    cell?: (value: any, row: any) => ComponentChild;
    useCellForDetail?: boolean;
}

// A per-row action shown in the "..." menu
export interface ActionItem {
    label: string;
    strong?: boolean;
    run: () => void;
}
