#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

containers:
  - name: binaries-container
    type: BinariesContainer
  - name: llvm-root
    type: LLVMRootContainer
  - name: model-header
    type: CBytesContainer

branches:
  files-imported:
    tasks:
      - pipe: ImportFiles
        arguments: [binaries-container]

  lift:
    from: files-imported
    tasks:
      - pipe: Lift
        arguments: [binaries-container, llvm-root]
      - pipe: PureLLVMPassesRootPipe
        arguments: [llvm-root]
        configuration:
          Passes:
            - globaldce
      - savepoint: lifted
        containers: [llvm-root]
        artifacts:
          - name: lift
            container: llvm-root

  emit-model-header:
    tasks:
      - pipe: ModelToHeader
        arguments: [model-header]
      - savepoint: model-header
        containers: [model-header]
        artifacts:
          - name: emit-model-header
            container: model-header
