#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

containers:
  - name: binaries-container
    type: BinariesContainer
  - name: llvm-root
    type: LLVMRootContainer
  - name: model-header
    type: CBytesContainer
  - name: model-types
    type: PTMLCTypeContainer
  - name: cfg-map
    type: CFGMap
  - name: llvm-functions
    type: LLVMFunctionContainer
  - name: hexdump
    type: HexDumpContainer
  - name: assembly-internal
    type: AssemblyInternalContainer
  - name: assembly
    type: AssemblyContainer
  - name: object-file
    type: ObjectFileContainer
  - name: translated
    type: TranslatedContainer
  - name: llvm-root-with-functions
    type: LLVMRootContainer

analyses:
  - apply-diff
  - verify-diff
  - set-model
  - verify-model
  - import-well-known-models
  - convert-functions-to-cabi

branches:
  files-imported:
    tasks:
      - pipe: import-files
        arguments: [binaries-container]
        analyses:
          - analysis: parse-binary
            containers: [binaries-container]

  lift:
    from: files-imported
    tasks:
      - pipe: lift
        arguments: [binaries-container, llvm-root]
      - pipe: pure-llvm-passes-root-pipe
        arguments: [llvm-root]
        configuration:
          passes:
            - globaldce
      - savepoint: lifted
        containers: [llvm-root]
        artifacts:
          - name: lift
            container: llvm-root
        analyses:
          - analysis: detect-abi
            containers: [llvm-root]

  collect-cfg:
    from: lift
    tasks:
      - pipe: collect-cfg
        arguments: [llvm-root, cfg-map]
      - savepoint: cfg-computed
        containers: [cfg-map]

  isolate:
    from: collect-cfg
    tasks:
      - pipe: isolate
        arguments: [cfg-map, llvm-root, llvm-functions]
      - pipe: attach-debug-info
        arguments: [cfg-map, llvm-functions]
      - savepoint: isolate
        containers: [llvm-functions]
        artifacts:
          - name: isolate
            container: llvm-functions

  enforce-abi:
    from: isolate
    tasks:
      - pipe: enforce-abi
        arguments: [cfg-map, llvm-functions]
      - pipe: pure-llvm-passes-pipe
        arguments: [llvm-functions]
        configuration:
          passes:
            - strip-debug-info-from-helpers
      # Note: we're running promote-csvs twice: it is important to run
      #       it before inline-helpers so that mem2reg can constant
      #       propagate helper arguments that are constant. This enables
      #       us to inline less code, in particular for helpers such as
      #       `cc_compute_c` and `cc_compute_all`.
      - pipe: promote-csvs
        arguments: [llvm-functions]
      - pipe: pure-llvm-passes-pipe
        arguments: [llvm-functions]
        configuration:
          passes:
            - mem2reg
            - inline-helpers
      - pipe: attach-debug-info
        arguments: [cfg-map, llvm-functions]
      - pipe: promote-csvs
        arguments: [llvm-functions]
      - pipe: pure-llvm-passes-pipe
        arguments: [llvm-functions]
        configuration:
          passes:
            - remove-exceptional-functions
            - strip-dead-debug-info
      - savepoint: enforce-abi
        containers: [llvm-functions]
        artifacts:
          - name: enforce-abi
            container: llvm-functions

  detect-stack-size:
    from: enforce-abi
    tasks:
      - pipe: pure-llvm-passes-pipe
        arguments: [llvm-functions]
        configuration:
          passes: [dce]
      - pipe: remove-lifting-artifacts
        arguments: [llvm-functions]
      - pipe: promote-init-csv-to-undef
        arguments: [llvm-functions]
      - pipe: inject-stack-size-probes-at-callsites
        arguments: [llvm-functions]
      - pipe: promote-stack-pointer
        arguments: [llvm-functions]
      - pipe: pure-llvm-passes-pipe
        arguments: [llvm-functions]
        configuration:
          passes:
            - dce
            - remove-extractvalues
            - simplify-cfg-with-hoist-and-sink
            - dse
            - instcombine
            - remove-extractvalues
            - sroa
            - instsimplify
            - jump-threading
            - licm
            - unreachableblockelim
            - instcombine
            - remove-extractvalues
            - early-cse
            - simplify-cfg-with-hoist-and-sink
            - early-type-shrinking
            - type-shrinking
            - early-cse
            - instsimplify
            - gvn
            - instsimplify
            - dse
            - dce
            # In Outliner we inject some store of opaque values before calls
            # targeting the link register/top of the stack: the goal is make
            # sure the stores writing the return address are dead.
            # After the previous optimization pipeline, dead store elimination
            # should have removed such stores, therefore, we can now drop
            # those injected by us too.
            - drop-opaque-return-address
            - globaldce
      - pipe: simplify-switch
        arguments: [binaries-container, llvm-functions]
      - savepoint: simplify-switch
        containers: [llvm-functions]
        artifacts:
          - name: simplify-switch
            container: llvm-functions
      - pipe: pure-llvm-passes-pipe
        arguments: [llvm-functions]
        configuration:
          passes:
            - remove-stack-alignment
            - instrument-stack-accesses
            - instcombine
            - remove-extractvalues
            - loop-rotate
            - loop-simplify
            - compute-stack-accesses-bounds
      - savepoint: detect-stack-size
        containers: [llvm-functions]
        analyses:
          - analysis: detect-stack-size
            containers: [llvm-functions]

  make-segment-ref:
    from: detect-stack-size
    tasks:
      - pipe: pure-llvm-passes-pipe
        arguments: [llvm-functions]
        configuration:
          passes: [hoist-struct-phis]
      - pipe: legacy-segregate-stack-accesses
        arguments: [llvm-functions]
      - pipe: pure-llvm-passes-pipe
        arguments: [llvm-functions]
        configuration:
          passes:
            - cleanup-stack-size-markers
            - dce
            - sroa
            - instcombine
            - remove-extractvalues
            - sroa
            - simplify-cfg-with-hoist-and-sink
            # loop-rotate rearranges loops in a way that should make it
            # easier to match do-while loops
            - loop-rotate
            - loop-rewrite-with-canonical-induction-variable
            - simplify-cfg-with-hoist-and-sink
            # don't run simplify-cfg{,-with-hoist-and-sink} after
            # loop-simplify because it kills the loop-simplify form causing
            # DLA not to identify arrays properly
            - loop-simplify
            - instcombine
            - remove-extractvalues
            - early-cse
            - dce
            - strip-dead-prototypes
            - split-overflow-intrinsics
            - dce
            - remove-llvmassume-calls
      - pipe: make-segment-ref
        arguments: [binaries-container, llvm-functions]
      - savepoint: make-segment-ref
        containers: [llvm-functions]
        artifacts:
          - name: make-segment-ref
            container: llvm-functions
        analyses:
          - analysis: analyze-data-layout
            containers: [llvm-functions]

  emit-model-header:
    tasks:
      - pipe: model-to-header
        arguments: [model-header]
      - savepoint: model-header
        containers: [model-header]
        artifacts:
          - name: emit-model-header
            container: model-header

  emit-type-definition:
    tasks:
      - pipe: generate-model-type-definition
        arguments: [model-types]
      - savepoint: model-types
        containers: [model-types]
        artifacts:
          - name: emit-type-definitions
            container: model-types

  hexdump:
    from: isolate
    tasks:
      - pipe: hex-dump
        arguments:
          - binaries-container
          - llvm-functions
          - cfg-map
          - hexdump
      - savepoint: hexdump
        containers: [hexdump]
        artifacts:
          - name: hexdump
            container: hexdump

  process-assembly:
    from: collect-cfg
    tasks:
      - pipe: process-assembly
        arguments: [binaries-container, cfg-map, assembly-internal]

  disassemble:
    from: process-assembly
    tasks:
      - pipe: yield-assembly
        arguments: [assembly-internal, assembly]
      - savepoint: disassemble
        containers: [assembly]
        artifacts:
          - name: disassemble
            container: assembly

  recompile:
    from: lift
    tasks:
      - pipe: link-support
        arguments: [llvm-root]
      - pipe: pure-llvm-passes-root-pipe
        arguments: [llvm-root]
        configuration:
          passes: [drop-opaque-return-address]
      - pipe: compile-root-module
        arguments: [llvm-root, object-file]
      - pipe: link-for-translation
        arguments: [binaries-container, object-file, translated]
      - savepoint: recompile
        containers: [translated]
        artifacts:
          - name: recompile
            container: translated

  recompile-isolated:
    from: isolate
    tasks:
      - pipe: invoke-isolated-functions
        arguments: [llvm-root, llvm-functions, llvm-root-with-functions]
      - pipe: link-support
        arguments: [llvm-root-with-functions]
      - pipe: pure-llvm-passes-root-pipe
        arguments: [llvm-root-with-functions]
        configuration:
          passes: [drop-opaque-return-address]
      - pipe: compile-root-module
        arguments: [llvm-root-with-functions, object-file]
      - pipe: link-for-translation
        arguments: [binaries-container, object-file, translated]
      - savepoint: recompile-isolated
        containers: [translated]
        artifacts:
          - name: recompile-isolated
            container: translated
