#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

containers:
  - name: binaries-container
    type: BinariesContainer

branches:
  files-imported:
    tasks:
      - pipe: ImportFiles
        arguments: [binaries-container]
