#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

containers:
  - name: binaries-container
    type: BinariesContainer
  - name: llvm-root
    type: LLVMRootContainer

branches:
  files-imported:
    tasks:
      - pipe: ImportFiles
        arguments: [binaries-container]

  lift:
    from: files-imported
    tasks:
      - pipe: Lift
        arguments: [binaries-container, llvm-root]
      - pipe: PureLLVMPassesRootPipe
        arguments: [llvm-root]
        configuration:
          Passes:
            - globaldce
      - savepoint: lifted
        containers: [llvm-root]
        artifacts:
          - name: lift
            container: llvm-root
