#pragma once

#include <variant>

#include "revng/TupleTree/TupleTreeDiff.h"

/*#-
This template file is distributed under the MIT License. See LICENSE.md for details.
The notice below applies to the generated files.
#*/
//
// This file is distributed under the MIT License. See LICENSE.md for details.
//

// This file is autogenerated! Do not edit it directly


namespace /*= namespace =*/ {

using AllTypes = std::variant<
/** for name in all_types|sort **/
/*= name =*//** if not loop.last **/,/** endif **/
/**- endfor **/
>;
} // namespace /*= ns =*/

