#pragma once

/*#-
This template file is distributed under the MIT License. See LICENSE.md for details.
The notice below applies to the generated files.
#*/
//
// This file is distributed under the MIT License. See LICENSE.md for details.
//

// This file is autogenerated! Do not edit it directly

// Forward declarations
/** for ns, names in ns_to_names.items() **/
namespace /*= ns =*/ {
/**- for name in names|sort **/
struct /*= name =*/;
/**- endfor **/
} // namespace /*= ns =*/
/** endfor **/

