#!/bin/bash

#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

PROGRAM=$1
FUNCTION=$2

VA=`readelf --wide -s $PROGRAM | grep $FUNCTION | grep GLOBAL | grep FUNC | head -n1 | awk -F' ' '{ print strtonum("0x" $2) }'`

echo $VA
