#!/usr/bin/env python3
#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

import os
import sys
from pathlib import Path

python_libs_dir = str(Path(__file__).parent.parent / "lib" / "python")
sys.path.insert(0, python_libs_dir)

prev_pythonpath = os.environ.get("PYTHONPATH")
os.environ["PYTHONPATH"] = python_libs_dir
if prev_pythonpath:
    os.environ["PYTHONPATH"] += ":" + prev_pythonpath

from revng.cli.revng import main

if __name__ == "__main__":
    sys.exit(main())
