#!/usr/bin/env python3
#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

import sys

from revng.cli.revng import main

if __name__ == "__main__":
    sys.exit(main())
